# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190304_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='editor',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imager',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
